apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-inv-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oms-inv-deployment
  template:
    metadata:
      labels:
        app: oms-inv-deployment
    spec:
      containers:
      - name: oms-inv-deployment
        image: azcrvfunctionpov.azurecr.io/oms-inv:latest
        env:
        - name: DATABASE_HOST
          value: "mysqldbvfunctionnprd.mysql.database.azure.com"
        - name: DATABASE_USERNAME
          value: "workshop"
        - name: DATABASE_PASSWORD
          value: "vFunction@2021!"
        - name: DATABASE_NAME    
          value: "oms1"     
---
apiVersion: v1
kind: Service
metadata:
  name: oms-inv-deployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: oms-inv-deployment
