apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-deployment-via-cicd
  labels:
    app: oms-deployment-via-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: omscicd
  template:
    metadata:
      labels:
        app: omscicd
    spec:
      containers:
      - name: omscicd
        image: azcrvfunctionpov.azurecr.io/oms-inv:latest
        ports:
        - containerPort: 80
