apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-deployment
  labels:
    app: oms-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oms
  template:
    metadata:
      labels:
        app: oms
    spec:
      containers:
      - name: oms
        image: azcrvfunctionpov.azurecr.io/oms-inv:latest
        ports:
        - containerPort: 8081
