apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-inv-deployment
  labels:
    app: oms-inv-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oms-inv-deployment
  template:
    metadata:
      labels:
        app: oms-inv-deployment
    spec:
      containers:
      - name: oms-inv-deployment
        image: azcrvfunctionpov.azurecr.io/oms-inv:latest
        ports:
        - containerPort: 80
