apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-inv-deployment
  labels:
    app: oms-inv-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oms-inv-deployment
  template:
    metadata:
      labels:
        app: oms-inv-deployment
    spec:
      containers:
      - name: oms-inv-deployment
        image: azcrvfunctionpov.azurecr.io/oms-inv:latest
        ports:
        - containerPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: inv-service
spec:
  selector:
    app: oms-inv-deployment
  ports:
    - port: 8765
      targetPort: 9376
  type: LoadBalancer
